### ISSUE TITLE
Add new enum values to enum columns when the definition changes

### ISSUE THREAD

**Issue by CmdrDats** [Yuppiechef/macaron#1]
If :

``` clojure
(defentity test
  (fields
    [status :enum ["Open" "Closed"]]))
```

changes to

``` clojure
(defentity test
  (fields
    [status :enum ["Open" "Started" "Closed"]]))
```

macaron needs to update the status enum and add the extra state.

**Comment by aislingvasey** [comment]
What should happen if the enum is totally changed (old values removed) and an error is thrown? Should the code check for existing data or just throw the SQL exception?

**Comment by CmdrDats** [comment]
Generally, I'd take the approach that it should look for new entries and just add them - If one is desperate to remove old enums it should be handled with a handcrafted patch since no single method will be right in all occasions.

So, if it gets totally changed, just add the new enums and leave the old ones alone.

This is consistent with the way fields currently get checked in macaron, new ones get added, removed ones get left alone assuming that if you really don't want them, you'll find a way to remove them.

**Comment by aislingvasey** [comment]
No problem. My next question was going to be do we need a drop column... but you answered that for me :)
