### ISSUE TITLE
Remove gensym'd argument names from defentityrecord generated functions

### ISSUE THREAD

**Issue by CmdrDats** [Yuppiechef/macaron#20]
Currently it generates the CRUD functions using gensym'd symbols, which ends up with cryptic looking autocomplete information, for example on the list functions:

``` clojure
([fld__244__auto__ val__2656__auto__])
```

Not ideal. It should be

``` clojure
([fld val])
```

The named query function autogeneration works correctly.

**Comment by crisptrutski** [comment]
Fixed
