### ISSUE TITLE
Create first-entity-query and single-entity-query functions for each entity

### ISSUE THREAD

**Issue by CmdrDats** [Yuppiechef/macaron#3]
Method signatures:

``` clojure
(defn first-entity-query [query param-map])
(defn single-entity-query [query param-map])
```

first-entity-query won't mind multiple results where single-entity-query should throw an exception if multiple results are found.

Note: entity is the name of the entity in question (defentity user..) will generate (defn first-user-query [...]) for instance.

**Comment by crisptrutski** [comment]
Ha! Same idea
